import 'package:warden/game/entities/effect.dart';
import 'package:warden/game/entities/stats.dart';
import 'package:warden/game/enums/enums.dart';
import 'package:warden/game/textos/diccionario.dart';

class ComboDefinition {
  final String id;
  final String sequence; // "123"
  final String name;
  final String description;
  final EffectType type;
  final int tier;
  final int powerCost;
  final List<EfectoClass> effects;

  const ComboDefinition({
    required this.id,
    required this.sequence,
    required this.name,
    required this.description,
    required this.type,
    required this.tier,
    required this.powerCost,
    required this.effects,
  });
}

ComboDefinition? findComboBySequence(String sequence) {
  return listadoCombos.firstWhere(
    (c) => c.sequence == sequence,
    orElse: () => ComboDefinition(
      id: '',
      sequence: '',
      name: '',
      description: '',
      type: EffectType.damage,
      tier: 0,
      powerCost: 0,
      effects: [],
    ),
  );
}

List<ComboDefinition> listadoCombos = [
  ComboDefinition(
    id: t('combo.spear.t1.id'),
    sequence: '12',
    name: t('combo.spear.t1.name'),
    type: EffectType.damage,
    tier: 1,
    description: t('combo.spear.t1.desc'),
    powerCost: 10,
    effects: [
      EfectoClass(
        nombre: t('combo.spear.t1.name'),
        tier: 1,
        vida: -50,
        type: EffectType.damage,
        target: EffectTarget.enemy,
        duracionInicial: 15,
        statsMod: StatsClass(),
      ),
    ],
  ),
  ComboDefinition(
    id: t('combo.spear.t2.id'),
    sequence: '121',
    name: t('combo.spear.t2.name'),
    description: t('combo.spear.t2.desc'),
    powerCost: 30,
    type: EffectType.damage,
    tier: 2,

    effects: [
      EfectoClass(
        nombre: t('combo.spear.t2.name'),
        tier: 2,
        vida: -100,
        type: EffectType.damage,
        target: EffectTarget.enemy,
        duracionInicial: 15,
        statsMod: StatsClass(),
      ),
    ],
  ),
  ComboDefinition(
    id: t('combo.spear.t3.id'),
    sequence: '1212',
    name: t('combo.spear.t3.name'),
    description: t('combo.spear.t3.desc'),
    powerCost: 70,
    type: EffectType.damage,
    tier: 3,

    effects: [
      EfectoClass(
        nombre: t('combo.spear.t3.name'),
        tier: 3,
        vida: -150,
        type: EffectType.damage,
        target: EffectTarget.enemy,
        duracionInicial: 15,
        statsMod: StatsClass(),
      ),
    ],
  ),
  ComboDefinition(
    id: t('combo.spear.t4.id'),
    sequence: '12121',
    name: t('combo.spear.t4.name'),
    description: t('combo.spear.t4.desc'),
    powerCost: 90,
    type: EffectType.damage,
    tier: 4,

    effects: [
      EfectoClass(
        nombre: t('combo.spear.t4.name'),
        tier: 4,
        vida: -200,
        type: EffectType.damage,
        target: EffectTarget.enemy,
        duracionInicial: 15,
        statsMod: StatsClass(),
      ),
    ],
  ),

  ComboDefinition(
    id: t('combo.shield.t1.id'),
    sequence: '21',
    name: t('combo.shield.t1.name'),
    description: t('combo.shield.t1.desc'),
    powerCost: 50,
    tier: 1,
    type: EffectType.heal,
    effects: [
      EfectoClass(
        nombre: t('combo.shield.t1.name'),
        tier: 1,
        vida: 50,
        type: EffectType.heal,
        target: EffectTarget.self,
        duracionInicial: 15,
        statsMod: StatsClass(),
      ),
    ],
  ),
  ComboDefinition(
    id: t('combo.shield.t2.id'),
    sequence: '212',
    name: t('combo.shield.t2.name'),
    description: t('combo.shield.t2.desc'),
    powerCost: 100,
    tier: 2,
    type: EffectType.heal,
    effects: [
      EfectoClass(
        nombre: t('combo.shield.t2.name'),
        tier: 2,
        vida: 100,
        type: EffectType.heal,
        target: EffectTarget.self,
        duracionInicial: 15,
        statsMod: StatsClass(),
      ),
    ],
  ),
  ComboDefinition(
    id: t('combo.shield.t3.id'),
    sequence: '2121',
    name: t('combo.shield.t3.name'),
    description: t('combo.shield.t3.desc'),
    powerCost: 150,
    tier: 3,
    type: EffectType.heal,
    effects: [
      EfectoClass(
        nombre: t('combo.shield.t3.name'),
        tier: 3,
        vida: 150,
        type: EffectType.heal,
        target: EffectTarget.self,
        duracionInicial: 15,
        statsMod: StatsClass(),
      ),
    ],
  ),
  ComboDefinition(
    id: t('combo.shield.t4.id'),
    sequence: '21212',
    name: t('combo.shield.t4.name'),
    description: t('combo.shield.t4.desc'),
    powerCost: 200,
    tier: 4,
    type: EffectType.heal,

    effects: [
      EfectoClass(
        nombre: t('combo.shield.t4.name'),
        tier: 4,
        vida: 200,
        type: EffectType.heal,
        target: EffectTarget.self,
        duracionInicial: 15,
        statsMod: StatsClass(),
      ),
    ],
  ),
  ComboDefinition(
    id: t('combo.power.t1.id'),
    sequence: '13121',
    name: t('combo.power.t1.name'),
    description: t('combo.power.t1.desc'),
    powerCost: 0,
    tier: 1,
    type: EffectType.power,
    effects: [
      EfectoClass(
        nombre: t('combo.power.t1.name'),
        tier: 1,
        vida: -50,
        power: 50,
        type: EffectType.power,
        target: EffectTarget.self,
        duracionInicial: 10,
        statsMod: StatsClass(),
      ),
    ],
  ),
  ComboDefinition(
    id: t('combo.shieldmaster.t1.id'),
    sequence: '2132',
    name: t('combo.shieldmaster.t1.name'),
    description: t('combo.shieldmaster.t1.desc'),
    powerCost: 50,
    tier: 1,
    type: EffectType.shieldmaster,
    effects: [
      EfectoClass(
        nombre: t('combo.shieldmaster.t1.name'),
        tier: 1,
        escudo: 50,
        type: EffectType.shieldmaster,
        target: EffectTarget.self,
        duracionInicial: 60,
        statsMod: StatsClass(),
      ),
    ],
  ),
  ComboDefinition(
    id: t('combo.shieldtactics.t1.id'),
    sequence: '2131',
    name: t('combo.shieldtactics.t1.name'),
    description: t('combo.shieldtactics.t1.desc'),
    powerCost: 50,
    tier: 1,
    type: EffectType.shiteldtactics,
    effects: [
      EfectoClass(
        nombre: t('combo.shieldtactics.t1.name'),
        tier: 1,
        feardazeinmune: 50,
        type: EffectType.shiteldtactics,
        target: EffectTarget.self,
        duracionInicial: 60,
        statsMod: StatsClass(),
      ),
    ],
  ),

  ComboDefinition(
    id: t('combo.fear.t1.id'),
    sequence: '32',
    name: t('combo.fear.t1.name'),
    description: t('combo.fear.t1.desc'),
    powerCost: 50,
    tier: 1,
    type: EffectType.fearStack,
    effects: [
      EfectoClass(
        nombre: t('combo.fear.t1.name'),
        tier: 1,
        vida: -50,
        target: EffectTarget.enemy,
        type: EffectType.fearStack,
        fear: 5,
        duracionInicial: 10,
        tiempo: 0,
        statsMod: StatsClass(),
      ),
      EfectoClass(
        nombre: t('combo.fear.t1.name'),
        tier: 5,
        vida: -50,
        type: EffectType.damage,
        target: EffectTarget.enemy,
        duracionInicial: 15,
        statsMod: StatsClass(),
      ),
    ],
  ),
  ComboDefinition(
    id: t('combo.fear.t2.id'),
    sequence: '323',
    name: t('combo.fear.t2.name'),
    description: t('combo.fear.t2.desc'),
    powerCost: 50,
    tier: 2,
    type: EffectType.fearStack,
    effects: [
      EfectoClass(
        nombre: t('combo.fear.t2.name'),
        tier: 2,
        vida: -100,
        target: EffectTarget.enemy,
        type: EffectType.fearStack,
        fear: 5,
        duracionInicial: 10,
        tiempo: 0,
        statsMod: StatsClass(),
      ),
      EfectoClass(
        nombre: t('combo.fear.t2.name'),
        tier: 6,
        vida: -100,
        type: EffectType.damage,
        target: EffectTarget.enemy,
        duracionInicial: 15,
        statsMod: StatsClass(),
      ),
    ],
  ),
  ComboDefinition(
    id: t('combo.fear.t3.id'),
    sequence: '3232',
    name: t('combo.fear.t3.name'),
    description: t('combo.fear.t3.desc'),
    powerCost: 50,
    tier: 3,
    type: EffectType.fearStack,
    effects: [
      EfectoClass(
        nombre: t('combo.fear.t3.name'),
        tier: 3,
        vida: -150,
        target: EffectTarget.enemy,
        type: EffectType.fearStack,
        fear: 5,
        duracionInicial: 10,
        tiempo: 0,
        statsMod: StatsClass(),
      ),
      EfectoClass(
        nombre: t('combo.fear.t3.name'),
        tier: 7,
        vida: -150,
        type: EffectType.damage,
        target: EffectTarget.enemy,
        duracionInicial: 15,
        statsMod: StatsClass(),
      ),
    ],
  ),
  ComboDefinition(
    id: t('combo.fear.t4.id'),
    sequence: '32323',
    name: t('combo.fear.t4.name'),
    description: t('combo.fear.t4.desc'),
    powerCost: 50,
    tier: 4,
    type: EffectType.fearStack,
    effects: [
      EfectoClass(
        nombre: t('combo.fear.t4.name'),
        tier: 4,
        vida: -200,
        target: EffectTarget.enemy,
        type: EffectType.fearStack,
        fear: 5,
        duracionInicial: 10,
        tiempo: 0,
        statsMod: StatsClass(),
      ),
      EfectoClass(
        nombre: t('combo.fear.t4.name'),
        tier: 8,
        vida: -200,
        type: EffectType.damage,
        target: EffectTarget.enemy,
        duracionInicial: 10,
        statsMod: StatsClass(),
      ),
    ],
  ),

  ComboDefinition(
    id: t('combo.daze.t1.id'),
    sequence: '31',
    name: t('combo.daze.t1.name'),
    description: t('combo.daze.t1.desc'),
    powerCost: 10,
    tier: 1,
    type: EffectType.dazeStack,
    effects: [
      EfectoClass(
        nombre: t('combo.daze.t1.name'),
        tier: 1,
        target: EffectTarget.enemy,
        type: EffectType.dazeStack,
        daze: 15,
        duracionInicial: 10,
        tiempo: 0,
        statsMod: StatsClass(),
      ),
    ],
  ),
  ComboDefinition(
    id: t('combo.daze.t2.id'),
    sequence: '313',
    name: t('combo.daze.t2.name'),
    description: t('combo.daze.t2.desc'),
    powerCost: 10,
    tier: 2,
    type: EffectType.dazeStack,
    effects: [
      EfectoClass(
        nombre: t('combo.daze.t2.name'),
        tier: 2,
        target: EffectTarget.enemy,
        type: EffectType.dazeStack,
        daze: 15,
        duracionInicial: 10,
        tiempo: 0,
        statsMod: StatsClass(),
      ),
    ],
  ),
  ComboDefinition(
    id: t('combo.daze.t3.id'),
    sequence: '3131',
    name: t('combo.daze.t3.name'),
    description: t('combo.daze.t3.desc'),
    powerCost: 10,
    tier: 3,
    type: EffectType.dazeStack,
    effects: [
      EfectoClass(
        nombre: t('combo.daze.t3.name'),
        tier: 3,
        target: EffectTarget.enemy,
        type: EffectType.dazeStack,
        daze: 15,
        duracionInicial: 10,
        tiempo: 0,
        statsMod: StatsClass(),
      ),
    ],
  ),
  ComboDefinition(
    id: t('combo.daze.t4.id'),
    sequence: '31313',
    name: t('combo.daze.t4.name'),
    description: t('combo.daze.t4.desc'),
    powerCost: 10,
    tier: 4,
    type: EffectType.dazeStack,
    effects: [
      EfectoClass(
        nombre: t('combo.daze.t4.name'),
        tier: 4,
        target: EffectTarget.enemy,
        type: EffectType.dazeStack,
        daze: 15,
        duracionInicial: 10,
        tiempo: 0,
        statsMod: StatsClass(),
      ),
    ],
  ),
  ComboDefinition(
    id: t('combo.statAtaque.t1.id'),
    sequence: '11111',
    name: t('combo.statAtaque.t1.name'),
    description: t('combo.statAtaque.t1.desc'),
    powerCost: 100,
    tier: 1,
    type: EffectType.statAtaque,
    effects: [
      EfectoClass(
        nombre: t('combo.statAtaque.t1.name'),
        tier: 1,
        target: EffectTarget.self,
        type: EffectType.statAtaque,
        duracionInicial: 30,
        tiempo: 0,
        statsMod: StatsClass(ataque: 10),
      ),
    ],
  ),
  ComboDefinition(
    id: t('combo.statDefensa.t1.id'),
    sequence: '22222',
    name: t('combo.statDefensa.t1.name'),
    description: t('combo.statDefensa.t1.desc'),
    powerCost: 100,
    tier: 1,
    type: EffectType.statDefensa,
    effects: [
      EfectoClass(
        nombre: t('combo.statDefensa.t1.name'),
        tier: 1,
        target: EffectTarget.self,
        type: EffectType.statDefensa,
        duracionInicial: 30,
        tiempo: 0,
        statsMod: StatsClass(defensa: 10),
      ),
    ],
  ),
  ComboDefinition(
    id: t('combo.statPoder.t1.id'),
    sequence: '33333',
    name: t('combo.statPoder.t1.name'),
    description: t('combo.statPoder.t1.desc'),
    powerCost: 100,
    tier: 4,
    type: EffectType.statPoder,
    effects: [
      EfectoClass(
        nombre: t('combo.statPoder.t1.name'),
        tier: 4,
        target: EffectTarget.self,
        type: EffectType.statPoder,
        duracionInicial: 30,
        tiempo: 0,
        statsMod: StatsClass(poder: 10),
      ),
    ],
  ),
  ComboDefinition(
    id: t('combo.statCuracion.t1.id'),
    sequence: '22233',
    name: t('combo.statCuracion.t1.name'),
    description: t('combo.statCuracion.t1.desc'),
    powerCost: 10,
    tier: 4,
    type: EffectType.statCuracion,
    effects: [
      EfectoClass(
        nombre: t('combo.statCuracion.t1.name'),
        tier: 4,
        target: EffectTarget.self,
        type: EffectType.statCuracion,
        duracionInicial: 30,
        tiempo: 0,
        statsMod: StatsClass(curacion: 10),
      ),
    ],
  ),
  ComboDefinition(
    id: t('combo.statPowerRegen.t1.id'),
    sequence: '11133',
    name: t('combo.statPowerRegen.t1.name'),
    description: t('combo.statPowerRegen.t1.desc'),
    powerCost: 10,
    tier: 4,
    type: EffectType.statPowerRegen,
    effects: [
      EfectoClass(
        nombre: t('combo.statPowerRegen.t1.name'),
        tier: 4,
        target: EffectTarget.self,
        type: EffectType.statPowerRegen,
        duracionInicial: 30,
        tiempo: 0,
        statsMod: StatsClass(powerRegen: 10),
      ),
    ],
  ),
];
