import 'package:warden/game/entities/combo.dart';
import 'package:warden/game/entities/effect.dart';
import 'package:warden/game/entities/stats.dart';
import 'package:warden/game/entities/enums.dart';
import 'package:warden/game/textos/diccionario.dart';

List<ComboDefinition> listadoCombosFist = [
  ComboDefinition(
    id: t('combo.fear.t1.id'),
    sequence: '32',
    name: t('combo.fear.t1.name'),
    description: t('combo.fear.t1.desc'),
    powerCost: 50,
    tier: 1,
    type: EffectType.fearStack,
    effects: [
      EfectoClass(
        nombre: t('combo.fear.t1.name'),
        tier: 1,
        vida: -50,
        target: EffectTarget.enemy,
        type: EffectType.fearStack,
        fear: 5,
        duracionInicial: 10,
        tiempo: 0,
        statsMod: StatsClass(),
      ),
      EfectoClass(
        nombre: t('combo.fear.t1.name'),
        tier: 5,
        vida: -50,
        type: EffectType.damage,
        target: EffectTarget.enemy,
        duracionInicial: 15,
        statsMod: StatsClass(),
      ),
    ],
  ),
  ComboDefinition(
    id: t('combo.fear.t2.id'),
    sequence: '323',
    name: t('combo.fear.t2.name'),
    description: t('combo.fear.t2.desc'),
    powerCost: 50,
    tier: 2,
    type: EffectType.fearStack,
    effects: [
      EfectoClass(
        nombre: t('combo.fear.t2.name'),
        tier: 2,
        vida: -100,
        target: EffectTarget.enemy,
        type: EffectType.fearStack,
        fear: 5,
        duracionInicial: 10,
        tiempo: 0,
        statsMod: StatsClass(),
      ),
      EfectoClass(
        nombre: t('combo.fear.t2.name'),
        tier: 6,
        vida: -100,
        type: EffectType.damage,
        target: EffectTarget.enemy,
        duracionInicial: 15,
        statsMod: StatsClass(),
      ),
    ],
  ),
  ComboDefinition(
    id: t('combo.fear.t3.id'),
    sequence: '3232',
    name: t('combo.fear.t3.name'),
    description: t('combo.fear.t3.desc'),
    powerCost: 50,
    tier: 3,
    type: EffectType.fearStack,
    effects: [
      EfectoClass(
        nombre: t('combo.fear.t3.name'),
        tier: 3,
        vida: -150,
        target: EffectTarget.enemy,
        type: EffectType.fearStack,
        fear: 5,
        duracionInicial: 10,
        tiempo: 0,
        statsMod: StatsClass(),
      ),
      EfectoClass(
        nombre: t('combo.fear.t3.name'),
        tier: 7,
        vida: -150,
        type: EffectType.damage,
        target: EffectTarget.enemy,
        duracionInicial: 15,
        statsMod: StatsClass(),
      ),
    ],
  ),
  ComboDefinition(
    id: t('combo.fear.t4.id'),
    sequence: '32323',
    name: t('combo.fear.t4.name'),
    description: t('combo.fear.t4.desc'),
    powerCost: 50,
    tier: 4,
    type: EffectType.fearStack,
    effects: [
      EfectoClass(
        nombre: t('combo.fear.t4.name'),
        tier: 4,
        vida: -200,
        target: EffectTarget.enemy,
        type: EffectType.fearStack,
        fear: 5,
        duracionInicial: 10,
        tiempo: 0,
        statsMod: StatsClass(),
      ),
      EfectoClass(
        nombre: t('combo.fear.t4.name'),
        tier: 8,
        vida: -200,
        type: EffectType.damage,
        target: EffectTarget.enemy,
        duracionInicial: 10,
        statsMod: StatsClass(),
      ),
    ],
  ),

  ComboDefinition(
    id: t('combo.daze.t1.id'),
    sequence: '31',
    name: t('combo.daze.t1.name'),
    description: t('combo.daze.t1.desc'),
    powerCost: 10,
    tier: 1,
    type: EffectType.dazeStack,
    effects: [
      EfectoClass(
        nombre: t('combo.daze.t1.name'),
        tier: 1,
        target: EffectTarget.enemy,
        type: EffectType.dazeStack,
        daze: 15,
        duracionInicial: 10,
        tiempo: 0,
        statsMod: StatsClass(),
      ),
    ],
  ),
  ComboDefinition(
    id: t('combo.daze.t2.id'),
    sequence: '313',
    name: t('combo.daze.t2.name'),
    description: t('combo.daze.t2.desc'),
    powerCost: 10,
    tier: 2,
    type: EffectType.dazeStack,
    effects: [
      EfectoClass(
        nombre: t('combo.daze.t2.name'),
        tier: 2,
        target: EffectTarget.enemy,
        type: EffectType.dazeStack,
        daze: 15,
        duracionInicial: 10,
        tiempo: 0,
        statsMod: StatsClass(),
      ),
    ],
  ),
  ComboDefinition(
    id: t('combo.daze.t3.id'),
    sequence: '3131',
    name: t('combo.daze.t3.name'),
    description: t('combo.daze.t3.desc'),
    powerCost: 10,
    tier: 3,
    type: EffectType.dazeStack,
    effects: [
      EfectoClass(
        nombre: t('combo.daze.t3.name'),
        tier: 3,
        target: EffectTarget.enemy,
        type: EffectType.dazeStack,
        daze: 15,
        duracionInicial: 10,
        tiempo: 0,
        statsMod: StatsClass(),
      ),
    ],
  ),
  ComboDefinition(
    id: t('combo.daze.t4.id'),
    sequence: '31313',
    name: t('combo.daze.t4.name'),
    description: t('combo.daze.t4.desc'),
    powerCost: 10,
    tier: 4,
    type: EffectType.dazeStack,
    effects: [
      EfectoClass(
        nombre: t('combo.daze.t4.name'),
        tier: 4,
        target: EffectTarget.enemy,
        type: EffectType.dazeStack,
        daze: 15,
        duracionInicial: 10,
        tiempo: 0,
        statsMod: StatsClass(),
      ),
    ],
  ),
];
